// Generated by CoffeeScript 1.7.1
(function() {
  var test;

  console.log("request.coffee");

  test = function() {
    return console.log("test");
  };

  module.exports = {
    test: test
  };

}).call(this);
