// Generated by CoffeeScript 1.7.1
(function() {
  var Stream, getTracks, startNewStream, stopStream, streamList;

  console.log("streamManager.coffee");

  Stream = require("./stream.js");

  streamList = [];

  startNewStream = function(artistName, artistId, mode) {
    var json, stream;
    console.log("startNewStream");
    console.log(artistName);
    console.log(artistId);
    stream = new Stream(artistName, artistId);
    console.log(stream.id);
    streamList[stream.id] = stream;
    console.log("streamList");
    console.log(streamList);
    json = {
      stream_id: stream.id,
      first_request_delay: stream.firstRequestDelay
    };
    return json;
  };

  getTracks = function(id, limit) {
    var json, stream, tracks;
    console.log("getTracks");
    stream = streamList[id];
    if (!stream) {
      return {
        "error": "stream " + id + " is not found."
      };
    } else {
      tracks = stream.popTracks(limit);
      json = {
        tracks: tracks
      };
      return json;
    }
  };

  stopStream = function(id) {
    var json, stream;
    console.log("stopStream");
    stream = streamList[id];
    if (!stream) {
      return {
        "error": "stream " + id + " is not found."
      };
    } else {
      stream.stop();
      delete streamList[id];
      console.log(streamList);
      json = {
        message: "stopped"
      };
      return json;
    }
  };

  module.exports = {
    startNewStream: startNewStream,
    getTracks: getTracks,
    stopStream: stopStream
  };

}).call(this);
