// Generated by CoffeeScript 1.7.1
(function() {
  var STOP_TIMEOUT, Stream, getTracks, setStopTimeout, startNewStream, stopStream, streamList;

  console.log("streamManager.coffee");

  Stream = require("./stream.js");

  streamList = [];

  startNewStream = function(artistName, artistId, mode) {
    var json, stream;
    console.log("startNewStream");
    console.log(artistName);
    console.log(artistId);
    stream = new Stream(artistName, artistId);
    console.log(stream.id);
    streamList[stream.id] = stream;
    console.log("streamList");
    console.log(streamList);
    setStopTimeout(stream);
    json = {
      stream_id: stream.id,
      first_request_delay: stream.firstRequestDelay
    };
    return json;
  };

  getTracks = function(id, limit) {
    var isError, json, stream, tracks;
    console.log("getTracks");
    stream = streamList[id];
    if (!stream) {
      return {
        "error": "stream " + id + " is not found."
      };
    } else {
      setStopTimeout(stream);
      tracks = stream.popTracks(limit);
      isError = stream.isError;
      json = {
        tracks: tracks,
        isError: isError
      };
      return json;
    }
  };

  stopStream = function(id) {
    var json, stream;
    console.log("stopStream");
    stream = streamList[id];
    if (!stream) {
      return {
        "error": "stream " + id + " is not found."
      };
    } else {
      stream.stop();
      delete streamList[id];
      console.log(streamList);
      json = {
        message: "stopped"
      };
      return json;
    }
  };

  STOP_TIMEOUT = 1000 * 60 * 15;

  setStopTimeout = function(stream) {
    if (stream.timeoutTimer) {
      clearTimeout(stream.timeoutTimer);
    }
    return stream.timeoutTimer = setTimeout(((function(_this) {
      return function() {
        stream.stop();
        return delete streamList[stream.id];
      };
    })(this)), STOP_TIMEOUT);
  };

  module.exports = {
    startNewStream: startNewStream,
    getTracks: getTracks,
    stopStream: stopStream
  };

}).call(this);
