// Generated by CoffeeScript 1.7.1
(function() {
  var log, req;

  log = function(s) {
    return console.log(s);
  };

  log("============= test.coffee =================");

  req = require('./request.js');

}).call(this);
