// Generated by CoffeeScript 1.7.1
(function() {
  var Stream, clog, stream4;

  clog = function(s) {
    return console.log(s);
  };

  clog("============= test.coffee =================");

  Stream = require("./stream.js");

  stream4 = new Stream("80kidz");

  setTimeout(((function(_this) {
    return function() {
      var newTracks;
      return newTracks = stream4.popTracks();
    };
  })(this)), stream4.firstRequestDelay);

}).call(this);
