// Generated by CoffeeScript 1.7.1
(function() {
  var YTParser, clog;

  clog = function(s) {
    return console.log(s);
  };

  clog("============= test.coffee =================");

  YTParser = require('./getYouTubeURL.js');

  YTParser.getUrlFromId("Q4MM80ZFlSA", function(videoURL) {
    clog("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
    return clog(videoURL);
  });

}).call(this);
